server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: moviesRoute 
          uri: http://localhost:8082/ 
          predicates:
            - Path=/movies/**
        - id: catalogRoute
          uri: http://localhost:8084/
          predicates:
            - Path=/catalog/**
            
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

info:
  app:
    name: gateway-service
    description: Primer parcial
    version: 1.0.0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
